"""ALTERANDO COLUNAS PARA CHAR

Revision ID: 9ebd36f8aa7d
Revises: 407a23281197
Create Date: 2026-04-30 09:30:15.050092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebd36f8aa7d'
down_revision: Union[str, Sequence[str], None] = '407a23281197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
